// SPDX-License-Identifier: Apache-2.0
// Fuzzer: fuzz_receipts — exercises the ouroboros lambda-gate receipt module
// Harness for Jazzer.js (ClusterFuzzLite, language: javascript)
//
// Tested surface:
//   - parseReceipt()  — JSON parsing + schema validation of raw receipt objects
//   - evaluateAxes()  — Λ-gate conjunctive AND evaluation across 9 axes
//   - computeLambda() — MIN reduction over axis values
//   - gateTransit()   — full end-to-end receipt evaluation + store path
//   - hashPayload()   — SHA-256 of arbitrary payloads
//   - verifyReceipt() — hash lookup + re-evaluation path

"use strict";

// Dynamic import path resolves after `pnpm exec tsc` in build.sh
// In CFL environment the built dist/ tree is on the require path.
const path = require("path");

let gate;
try {
  // Try compiled dist first (CFL build)
  gate = require(path.join(__dirname, "../../dist/runtime/lambda-gate/src/gate"));
} catch (_) {
  // Fall back to ts-node in CI dev mode (not available in CFL; harmless failure)
  gate = null;
}

/**
 * Jazzer.js fuzz entry point.
 * `data` is a Buffer of raw fuzzer-generated bytes.
 */
module.exports.fuzz = function fuzz(data) {
  if (!gate) return; // not built yet — skip silently

  const {
    parseReceipt,
    evaluateAxes,
    computeLambda,
    gateTransit,
    hashPayload,
    verifyReceipt,
  } = gate;

  // --- 1. Attempt to parse the raw bytes as a JSON receipt ---
  let raw;
  try {
    raw = JSON.parse(data.toString("utf8"));
  } catch (_) {
    // Invalid JSON — still useful to exercise the rejection path
    raw = data.toString("utf8");
  }

  // --- 2. Hash the raw payload (must never throw) ---
  try {
    hashPayload(raw);
  } catch (_) {/* expected for non-serialisable inputs */}

  // --- 3. Attempt receipt parse + gate transit ---
  try {
    const result = gateTransit(raw);
    // If it passed, verify via hash
    if (result && result.receipt && result.stored) {
      verifyReceipt(result.receipt.hash);
    }
  } catch (_) {/* validation rejections are expected */}

  // --- 4. Build synthetic axes from the first 9 bytes ---
  const AXIS_KEYS = [
    "moralGrounding",
    "measurabilityHonesty",
    "epistemicHumility",
    "systemicResilience",
    "operationalTransparency",
    "adaptiveLearning",
    "stakeholderAlignment",
    "regulatoryReadiness",
    "innovationBalance",
  ];
  const syntheticAxes = {};
  for (let i = 0; i < AXIS_KEYS.length; i++) {
    // Map byte value 0–255 to float 0.0–1.0
    syntheticAxes[AXIS_KEYS[i]] = (data[i % data.length] ?? 128) / 255;
  }

  // --- 5. Evaluate synthetic axes directly ---
  try {
    computeLambda(syntheticAxes);
    evaluateAxes(syntheticAxes);
  } catch (_) {/* unexpected — surface as a finding */}
};
